import Navbar from '@/components/nav-bar';
import './globals.css'
import type { Metadata } from 'next'
import { Urbanist } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs';
import { cn } from '@/lib/utils';
import ToastProvider from '@/provider/toast-provider';
import ModalProvider from '@/provider/modal-provider';

const font = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={font.className}>
          <ToastProvider />
          <ModalProvider />
          {children}
        </body>
      </html>
    </ClerkProvider>

  )
}
